export const moods = {
  calm:    { label: "Calm",    tempo: [60, 76],   mode: "major",  density: 0.15, rhythm: false, rhythmDensity: 0,    seventh: false, waveform: "sine",     reverb: 0.60, bassPattern: "whole" },
  night:   { label: "Night",   tempo: [70, 88],   mode: "dorian", density: 0.25, rhythm: true,  rhythmDensity: 0.58, seventh: true,  waveform: "triangle", reverb: 0.50, bassPattern: "half" },
  jazz:    { label: "Jazz",    tempo: [96, 132],  mode: "major",  density: 0.35, rhythm: true,  rhythmDensity: 0.70, seventh: true,  waveform: "triangle", reverb: 0.30, bassPattern: "walk", secondaryDominant: true },
  upbeat:  { label: "Upbeat",  tempo: [110, 128], mode: "major",  density: 0.45, rhythm: true,  rhythmDensity: 0.84, seventh: false, waveform: "sawtooth", reverb: 0.25, bassPattern: "walk" },
  dream:   { label: "Dream",   tempo: [56, 72],   mode: "major",  density: 0.22, rhythm: false, rhythmDensity: 0,    seventh: true,  waveform: "sine",     reverb: 0.78, bassPattern: "whole" },
  mist:    { label: "Mist",    tempo: [64, 80],   mode: "minor",  density: 0.18, rhythm: false, rhythmDensity: 0,    seventh: true,  waveform: "triangle", reverb: 0.72, bassPattern: "whole" },
  pulse:   { label: "Pulse",   tempo: [88, 108],  mode: "dorian", density: 0.32, rhythm: true,  rhythmDensity: 0.92, seventh: false, waveform: "sawtooth", reverb: 0.24, bassPattern: "half" },
  sunrise: { label: "Sunrise", tempo: [78, 96],   mode: "major",  density: 0.30, rhythm: true,  rhythmDensity: 0.46, seventh: true,  waveform: "triangle", reverb: 0.42, bassPattern: "half" },
  lunar:   { label: "Lunar",   tempo: [52, 68],   mode: "dorian", density: 0.13, rhythm: false, rhythmDensity: 0,    seventh: true,  waveform: "sine",     reverb: 0.84, bassPattern: "whole" },
  drift:   { label: "Drift",   tempo: [74, 92],   mode: "major",  density: 0.27, rhythm: true,  rhythmDensity: 0.34, seventh: true,  waveform: "sine",     reverb: 0.66, bassPattern: "half" },
  noir:    { label: "Noir",    tempo: [82, 102],  mode: "minor",  density: 0.29, rhythm: true,  rhythmDensity: 0.52, seventh: true,  waveform: "triangle", reverb: 0.46, bassPattern: "walk", secondaryDominant: true },
  spark:   { label: "Spark",   tempo: [124, 144], mode: "major",  density: 0.50, rhythm: true,  rhythmDensity: 0.96, seventh: false, waveform: "sawtooth", reverb: 0.18, bassPattern: "walk" },
  ember:   { label: "Ember", tempo: [68,84], mode: "minor", density: .21, rhythm: true, rhythmDensity: .28, seventh: true, waveform: "triangle", reverb: .58, bassPattern: "whole" },
  tide:    { label: "Tide", tempo: [72,90], mode: "dorian", density: .24, rhythm: true, rhythmDensity: .38, seventh: true, waveform: "sine", reverb: .70, bassPattern: "half" },
  forest:  { label: "Forest", tempo: [66,82], mode: "major", density: .20, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "triangle", reverb: .64, bassPattern: "whole" },
  snow:    { label: "Snow", tempo: [50,66], mode: "major", density: .11, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "sine", reverb: .88, bassPattern: "whole" },
  rain:    { label: "Rain", tempo: [76,94], mode: "minor", density: .34, rhythm: true, rhythmDensity: .72, seventh: true, waveform: "sine", reverb: .68, bassPattern: "half" },
  dusk:    { label: "Dusk", tempo: [62,78], mode: "minor", density: .17, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "triangle", reverb: .76, bassPattern: "whole" },
  aurora:  { label: "Aurora", tempo: [80,100], mode: "major", density: .31, rhythm: true, rhythmDensity: .42, seventh: true, waveform: "sine", reverb: .74, bassPattern: "half" },
  velvet:  { label: "Velvet", tempo: [70,86], mode: "minor", density: .23, rhythm: true, rhythmDensity: .30, seventh: true, waveform: "triangle", reverb: .62, bassPattern: "whole" },
  glass:   { label: "Glass", tempo: [92,112], mode: "dorian", density: .38, rhythm: true, rhythmDensity: .66, seventh: false, waveform: "sine", reverb: .48, bassPattern: "half" },
  bloom:   { label: "Bloom", tempo: [84,104], mode: "major", density: .36, rhythm: true, rhythmDensity: .50, seventh: true, waveform: "triangle", reverb: .44, bassPattern: "half" },
  canyon:  { label: "Canyon", tempo: [74,92], mode: "minor", density: .19, rhythm: true, rhythmDensity: .36, seventh: false, waveform: "sawtooth", reverb: .82, bassPattern: "whole" },
  harbor:  { label: "Harbor", tempo: [64,82], mode: "major", density: .18, rhythm: true, rhythmDensity: .24, seventh: true, waveform: "sine", reverb: .68, bassPattern: "whole" },
  meadow:  { label: "Meadow", tempo: [76,94], mode: "major", density: .28, rhythm: false, rhythmDensity: 0, seventh: false, waveform: "triangle", reverb: .54, bassPattern: "half" },
  cloud:   { label: "Cloud", tempo: [58,74], mode: "major", density: .14, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "sine", reverb: .86, bassPattern: "whole" },
  starlit: { label: "Starlit", tempo: [68,86], mode: "dorian", density: .26, rhythm: true, rhythmDensity: .32, seventh: true, waveform: "triangle", reverb: .78, bassPattern: "half" },
  echo:    { label: "Echo", tempo: [82,102], mode: "minor", density: .30, rhythm: true, rhythmDensity: .44, seventh: true, waveform: "sine", reverb: .90, bassPattern: "half" },
  orbit:   { label: "Orbit", tempo: [100,120], mode: "dorian", density: .40, rhythm: true, rhythmDensity: .78, seventh: false, waveform: "sawtooth", reverb: .36, bassPattern: "walk" },
  neon:    { label: "Neon", tempo: [116,136], mode: "minor", density: .47, rhythm: true, rhythmDensity: .94, seventh: false, waveform: "sawtooth", reverb: .20, bassPattern: "walk" },
  copper:  { label: "Copper", tempo: [88,106], mode: "minor", density: .33, rhythm: true, rhythmDensity: .60, seventh: true, waveform: "triangle", reverb: .34, bassPattern: "walk", secondaryDominant: true },
  ivory:   { label: "Ivory", tempo: [60,78], mode: "major", density: .16, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "sine", reverb: .58, bassPattern: "whole" },
  moss:    { label: "Moss", tempo: [70,88], mode: "dorian", density: .22, rhythm: true, rhythmDensity: .26, seventh: true, waveform: "triangle", reverb: .66, bassPattern: "whole" },
  ocean:   { label: "Ocean", tempo: [62,80], mode: "major", density: .25, rhythm: true, rhythmDensity: .34, seventh: true, waveform: "sine", reverb: .82, bassPattern: "half" },
  desert:  { label: "Desert", tempo: [86,104], mode: "dorian", density: .27, rhythm: true, rhythmDensity: .48, seventh: false, waveform: "sawtooth", reverb: .52, bassPattern: "half" },
  frost:   { label: "Frost", tempo: [54,70], mode: "minor", density: .12, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "sine", reverb: .92, bassPattern: "whole" },
  lantern: { label: "Lantern", tempo: [72,90], mode: "major", density: .24, rhythm: true, rhythmDensity: .22, seventh: true, waveform: "triangle", reverb: .60, bassPattern: "whole" },
  river:   { label: "River", tempo: [90,108], mode: "major", density: .37, rhythm: true, rhythmDensity: .64, seventh: false, waveform: "sine", reverb: .50, bassPattern: "half" },
  thunder: { label: "Thunder", tempo: [106,126], mode: "minor", density: .43, rhythm: true, rhythmDensity: .98, seventh: false, waveform: "sawtooth", reverb: .22, bassPattern: "walk" },
  breeze:  { label: "Breeze", tempo: [78,96], mode: "major", density: .29, rhythm: true, rhythmDensity: .40, seventh: false, waveform: "triangle", reverb: .56, bassPattern: "half" },
  solstice:{ label: "Solstice", tempo: [64,82], mode: "dorian", density: .20, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "sine", reverb: .80, bassPattern: "whole" },
  equinox: { label: "Equinox", tempo: [84,102], mode: "major", density: .32, rhythm: true, rhythmDensity: .52, seventh: true, waveform: "triangle", reverb: .48, bassPattern: "half" },
  comet:   { label: "Comet", tempo: [120,140], mode: "dorian", density: .48, rhythm: true, rhythmDensity: .90, seventh: false, waveform: "sawtooth", reverb: .26, bassPattern: "walk" },
  halo:    { label: "Halo", tempo: [56,72], mode: "major", density: .15, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "sine", reverb: .94, bassPattern: "whole" },
  monsoon: { label: "Monsoon", tempo: [96,116], mode: "minor", density: .42, rhythm: true, rhythmDensity: .86, seventh: false, waveform: "sawtooth", reverb: .40, bassPattern: "walk" },
  twilight:{ label: "Twilight", tempo: [66,84], mode: "minor", density: .21, rhythm: true, rhythmDensity: .20, seventh: true, waveform: "triangle", reverb: .74, bassPattern: "whole" },
  chapel:  { label: "Chapel", tempo: [52,68], mode: "minor", density: .13, rhythm: false, rhythmDensity: 0, seventh: true, waveform: "sine", reverb: .96, bassPattern: "whole" },
  arcade:  { label: "Arcade", tempo: [128,148], mode: "major", density: .52, rhythm: true, rhythmDensity: 1, seventh: false, waveform: "square", reverb: .14, bassPattern: "walk" },
  voyage:  { label: "Voyage", tempo: [88,106], mode: "dorian", density: .34, rhythm: true, rhythmDensity: .56, seventh: true, waveform: "triangle", reverb: .58, bassPattern: "half" },
  oasis:   { label: "Oasis", tempo: [72,90], mode: "major", density: .26, rhythm: true, rhythmDensity: .36, seventh: true, waveform: "sine", reverb: .72, bassPattern: "half" },
  phantom: { label: "Phantom", tempo: [76,94], mode: "minor", density: .24, rhythm: true, rhythmDensity: .42, seventh: true, waveform: "triangle", reverb: .88, bassPattern: "whole", secondaryDominant: true },
  fiesta:  { label: "Fiesta", tempo: [118,138], mode: "major", density: .49, rhythm: true, rhythmDensity: .98, seventh: true, waveform: "sawtooth", reverb: .20, bassPattern: "walk", secondaryDominant: true },
};

export const randomTempo = (mood) => Math.round(mood.tempo[0] + Math.random() * (mood.tempo[1] - mood.tempo[0]));
